# Generated by Django 5.2 on 2025-07-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_medicalhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
